sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMemLondM5xvNGUTDcD
    access-key-secret: yBEAUx6Dc2AJjQ283NuhXRro04kmMu
    bucket-name: sky-sjy
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10